name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.rst'
      - '**/*.md'
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: Code linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run code linter
        run: |
          pip install -r requirements.txt
          flake8 flask_redis
          pylint flask_redis
